### ISSUE TITLE
Update Postman for Context Providers tutorial

### ISSUE THREAD

**Issue by henry2man** [Fiware/tutorials.Step-by-Step#22]
I'm using the Postman Collections from the Step-by-step Context Providers tutorial and I noticed that published collection is old. The most obvious problem is that the published Postman collection still uses NGSI v1 queries.

You'll find the updated collection here: https://github.com/FIWARE/tutorials.Context-Providers/blob/master/FIWARE%20Context%20Providers.postman_collection.json

The non-updated postman collection referred in the docs: https://app.getpostman.com/run-collection/7c9bed4bd2ce5213a80b

This is a "cross issue" already posted here: https://github.com/FIWARE/tutorials.Context-Providers/issues/16

**Comment by jason-fox** [comment]
The collection has been updated: https://github.com/FIWARE/tutorials.Context-Providers/issues/16
