### ISSUE TITLE
Raw/editable files of diagrams

### ISSUE THREAD

**Issue by kosgobakis** [Fiware/tutorials.Step-by-Step#45]
Thanks a lot for the great tutorials.

Is it possible to share the raw/editable files that you use to create the various connection/network diagrams that are included into the tutorials ie https://fiware.github.io/tutorials.PEP-Proxy/img/pep-proxy-orion.png

**Comment by jason-fox** [comment]
I don't think that is possible. The raw images are available on the GH-PAGES branch of course, however they have been generated using [Lucid Chart](https://lucid.app/documents) which doesn't offer document sharing for free. The entity diagrams which can also be found on the GH-PAGES have been written using PUML which should be editable on the [plantuml.com server](https://plantuml.com/)

The diagrams are just box and line drawings, so it shouldn't take too long to create your own on Lucid Chart though.
