### ISSUE TITLE
Stock Management Frontend not found

### ISSUE THREAD

**Issue by ranim-n** [Fiware/tutorials.Step-by-Step#47]
when trying to acess the Stock Managment Frontend with the link provided here : https://github.com/FIWARE/tutorials.Working-with-Linked-Data/tree/master?tab=readme-ov-file#stock-management-frontend   it cannot be found.

**Comment by jason-fox** [comment]
Fixed https://github.com/FIWARE/tutorials.NGSI-v2/commit/0410d9f76e and others.
